### ISSUE TITLE
June 2018 Team meeting

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/team-compass#43] opened 2018-06-25 19:22 UTC
How does Thursday, June 28 at 21:00 CEST, 12:00 PDT (noon) sound?

**Comment by betatim** [comment] 2018-06-25 20:37
I probably can't make it for 6pm, only a few hours later.

**Comment by jzf2101** [comment] 2018-06-25 21:14
@consideRatio @minrk can you do later that day? When would be ok for you @betatim ?

**Comment by consideRatio** [comment] 2018-06-25 21:29
Sure can @jzf2101 !

**Comment by betatim** [comment] 2018-06-25 21:46
I can probably make 9pm.

**Comment by jzf2101** [comment] 2018-06-25 22:31
9pm is noon PDT- @yuvipanda could you attend then? Is that too late for you @minrk @consideRatio ?

**Comment by consideRatio** [comment] 2018-06-25 23:00
Works fine!

**Comment by choldgraf** [comment] 2018-06-25 23:57
I can make it this Thursday @ 9:00 PDT

**Comment by jzf2101** [comment] 2018-06-26 00:03
I think our current proposal is 12pm PDT

**Comment by choldgraf** [comment] 2018-06-26 05:40
@jzf2101 could you please edit the top-level comment with whatever the latest time proposal is?

**Comment by betatim** [comment] 2018-06-26 14:46
Updated the comment. Is there urgent business that needs addressing this week? Otherwise I would lobby for waiting till next week to give people a bit more time to make a hole in their diary.

Topics I'd like to discuss:
* what if I was to receive $20000 (or more) in cloud credits, how could they go to running mybinder.org?
* how do we try out https://cloud.google.com/compute/docs/instances/preemptible to see how disruptive it would be to users and how much we would end up saving?

**Comment by choldgraf** [comment] 2018-06-26 15:11
I'm also +1 on waiting until next week.

re: pre-emptible VMs, that's an interesting idea. it [looks like you can use them with k8s](https://cloud.google.com/kubernetes-engine/docs/concepts/preemptible-vm). However it seems like it'd be really frustrating for users if their pods just randomly died...

topics I'd like to cover:

Discussion points / updates:
1. I'd like to get some momentum behind the "binder sustainability" conversation. Or at least to recap what we discussed @ the dev meeting.
2. Update on the scipy paper
3. @jzf2101 should give an update on the reproducible environments paper she's been spearheading!
4. Update on the PEARC conference tutorial that we'll be giving in pittsburgh
5. Cost model + projections for our $$$ burn rate

**Comment by consideRatio** [comment] 2018-06-26 15:37
@betatim I figure preemptible nodes make sense as the cost is reduced with about 70% if i recall correctly. The nodes should preferably not consistently get shut down after the 24 hour limit though, but instead phased out before then. To do that, they must be made small enough, and perhaps be combined with a custom scheduler that schedules on fresh nodes over old nodes to allow them to be phased out. 

Also, with k8s 1.11 arriving on google cloud in perhaps a month we will have access to pod priority stuff that can be of use to scale up / down as well using a kubernetes aware scaling.

I'm currently working on scaling / scheduling stuff within the z2jh repo.

**Comment by minrk** [comment] 2018-06-26 16:24
I cannot make it on Wednesday or Thursday this week, but can make Monday-Wednesday next week.

**Comment by jzf2101** [comment] 2018-06-26 18:20
Wednesday next week is July 4 so I think maybe Monday or Tuesday works best?

**Comment by consideRatio** [comment] 2018-06-26 19:13
Monday would be good for me next week! Tuesday may be possible but would cause a lot of friction.

**Comment by jzf2101** [comment] 2018-06-26 20:35
How does 18:00 CEST 9:00 PDT on Monday sound?

**Comment by jzf2101** [comment] 2018-06-28 04:40
@betatim When would work for you instead.  Keep in mind Wednesday is a 🇺🇸  holiday

**Comment by betatim** [comment] 2018-06-28 05:43
Can we do Tuesday at 6pm? I am travelling on Monday.

**Comment by minrk** [comment] 2018-06-28 12:15
Any time both Monday and Tuesday works for me

**Comment by jzf2101** [comment] 2018-06-28 15:44
Tuesday at 6pm is 9am Tuesday Pacific - does that work with @consideRatio and @yuvipanda ?

**Comment by minrk** [comment] 2018-07-02 10:35
I cannot make Thursday or Friday

**Comment by betatim** [comment] 2018-07-02 11:06
No one has mentioned anything that is time critical, so I would propose we postpone to Tuesday or Thursday next week (10 or 12 July). I think with this many people with busy schedules we need at least a week or more to find a hole in everyone's schedule.

**Comment by minrk** [comment] 2018-07-02 13:07
SciPy is next week, so I'll be traveling or at the conference all week. I will be in the US timezone (Berkeley, in fact) without other commitments the following week.

**Comment by betatim** [comment] 2018-07-02 13:17
Should we aim for 17 or 19th then? I think there are several people attending SciPy so no point aiming for next week.

**Comment by minrk** [comment] 2018-07-02 13:30
That works for me

**Comment by jzf2101** [comment] 2018-07-02 18:37
I'm ok with that

**Comment by consideRatio** [comment] 2018-07-02 19:18
+1

**Comment by betatim** [comment] 2018-07-02 19:21
I created a new issue for July. I think it will be better to transfer agenda items to there and not have a long issue that starts with scheduling a June meeting and then eventually is about a July meeting.

**Closed** 2018-07-02 19:34 UTC
