### ISSUE TITLE
Standardised issue templates for all JupyterHub repositories

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#271] opened 2020-03-27 12:40 UTC
Following on from https://github.com/jupyterhub/jupyterhub/pull/3001.
I looked into whether we could define this once at the organisation level instead of updating each repo individually. This suggests we could by creating a new repository called `.github`:
https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

Shall we give it go using the files from https://github.com/jupyterhub/jupyterhub/pull/3001 ?

**Comment by GeorgianaElena** [comment] 2020-03-27 12:59
What do you think about also using a bot like [ranger](https://github.com/marketplace/ranger) or [support](https://github.com/apps/support) to close and comment an issue once we label it with *Technical Support* or *Should be on Discourse*?

We can use @betatim's suggested text as the comment to the closed issue:
 
> Hi there 👋!
> 
> Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)
> 
> Thanks!

**Comment by manics** [comment] 2020-03-27 13:53
I created a repo to try out the [support](https://github.com/apps/support) bot: https://github.com/manicstreetpreacher/test-bots/
Create an issue, then label it `support` and the bot should do it's work.
I'll add people as collaborators so you can try out the labels.

**Comment by GeorgianaElena** [comment] 2020-03-27 14:17
I just tried it and it works :confetti_ball: 
One question: can the issue be re-opened by the maintainer after the bot closed it (as a collaborator, I couldn't do it)? I'm thinking that there might be situations where a support question might uncover a bug and we'd want to come back to the GitHub issue and post the resolution.

**Comment by manics** [comment] 2020-03-27 15:29
@GeorgianaElena I've changed you from`Triage` to `Maintain`:
![image](https://user-images.githubusercontent.com/1644105/77772197-a911fb80-703f-11ea-94c6-3483bed935da.png)
Can you try now?

**Comment by GeorgianaElena** [comment] 2020-03-27 15:38
Yep, it worked :sparkles:

**Comment by choldgraf** [comment] 2020-03-27 16:38
Two quick things:

1. I think it's a good idea to standardize issue / PR templates. My one concern is that there is value in having repository-specific information in some of them. But then again, I don't know that we really make strong use of this, and in reality it's more common that we have the same high-level information but presented slightly differently in each repo. So I think I'm OK with this as long as others agree as well.
2. For a bot, we need to be careful with the language. For example, in @manics's bot, it says "Can we...", but then it also closes the issue. That feels a bit passive-aggressive to me :-) I know this sounds like silly wordsmithing, but maybe if it were "Can you please..." instead of "can we" then it would be more like a request than a question, in which case closing the issue is reasonable.
3. Does anybody else think that @GeorgianaElena celebration emoji 🎊 looks like a pacman vomiting confetti? #importantquestions

**Comment by sgibson91** [comment] 2020-03-27 16:48
@choldgraf 100% agree on 3 :joy: I also agree that tone of the message is super important in how people feel when a random bot closes their issue. Maybe vomiting pacmans will be useful there too?

**Comment by GeorgianaElena** [comment] 2020-03-27 16:54
It was just a normal celebration emoji in my head. Now, I can't see anything else but the vomiting pacman 😂

**Comment by betatim** [comment] 2020-03-27 17:02
We should most definitely tweak the text. I made one suggestion in https://github.com/manicstreetpreacher/test-bots/issues/4#issuecomment-605106099 I think the bot should start with explaining what just happened and then stating what the reader can do to get their problem solved:
* "I closed this because it was labelled as a support question" and
* "Please repost this in the forum".
Then explain a bit more why we use this policy. On a nteract repository a bot used to close&comment on stale issues. It used to say something like "the resource we are lacking is time. sorry we didn't get around to looking at this. You can help create more time for the maintainers by doing X, Y or Z." I used to like that because it told people something they could do to help improve the situation.

**Comment by choldgraf** [comment] 2020-03-27 17:17
@betatim I like that text, I think it's more to-the-point 👍

**Comment by manics** [comment] 2020-03-27 21:42
I've updated the text: https://github.com/manicstreetpreacher/test-bots/commit/c259a011fed809a7cbdc6e346d41f2c75448ea13

I also discovered that removing the `support` label causes the bot to re-open the issue.

**Comment by GeorgianaElena** [comment] 2020-04-03 13:29
I created a [`.github` repository](https://github.com/GeorgianaElena/.github) that has  the `support` bot customized by @manics and the issue templates recently added to JH.

As @manics suggested in this comment https://github.com/jupyterhub/team-compass/issues/271#issue-589106472, having a `.github` repo at the the org level, will create a set of default community health files that will be applied to all the repos within the organization (if a repo doesn't overwrite them).

Two things that I think are worth mentioning:
* The `.github` repository should work on a regular account also (not just an organization). However, it seems that for my account it doesn't have any effect on any of my repositories. People with similar issues created [this thread](https://github.community/t5/How-to-use-Git-and-GitHub/Default-community-files-ignores-issue-templates/m-p/43809) and from what I understand a fix is on the way.
P.S. I think it's possible that if we decide to transfer this repo at the org level it will work just fine :woman_shrugging:
* I'm note sure if we can also standardize the bot through this `.github` repo as its config isn't in the list of supported file types [the docs](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types).

**Comment by manics** [comment] 2020-04-03 15:29
> I'm note sure if we can also standardize the bot through this .github repo as its config isn't in the list of supported file types

Yes you can! See https://github.com/apps/support
> Create .github/support.yml in the default branch to enable the app, or add it at the same file path to a repository named .github.

**Comment by GeorgianaElena** [comment] 2020-04-06 14:19
Should I transfer the `.github` repo to the org and see the bot and issue templates in action :rocket:  for all the JupyterHub repositories? WDYT?

**Comment by manics** [comment] 2020-04-06 14:29
Sounds good to me!

**Comment by GeorgianaElena** [comment] 2020-04-08 07:39
Turns out there was a `.github` repo already in the JupyterHub org, so I opened a PR there (https://github.com/jupyterhub/.github/pull/1).

**Closed** 2020-04-10 13:40 UTC
